# Generated by Django 5.1.4 on 2024-12-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.supply')),
            ],
        ),
    ]
