# Generated by Django 5.1.4 on 2024-12-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.organization'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Server Admin', 'Server Admin'), ('Organization Admin', 'Org Admin'),
                                            ('Organization User', 'Org User')], default='Server Admin', max_length=50),
        ),
    ]
