# Generated by Django 5.1.4 on 2024-12-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplydata',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supply'),
        ),
        migrations.AddField(
            model_name='supply',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
            preserve_default=False,
        ),
    ]
