# Generated by Django 5.1.4 on 2024-12-25 18:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('Server Admin', 'Server Admin'), ('Organization Admin', 'Organization Admin'),
                         ('Organization User', 'Organization User')], default='Server Admin', max_length=50),
        ),
    ]
