# Generated by Django 5.1.4 on 2024-12-25 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_alter_customuser_managers_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
