# Generated by Django 5.1.4 on 2024-12-25 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
