name: supply_monitor
description: App designed to monitor resource usage across VWP facilities.

version: 1.0.0

environment:
  sdk: ">=3.4.3"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: ^27.2.5
  fl_chart: ^0.69.2
  provider: ^6.1.2
  shared_preferences: ^2.0.18
  url_launcher: ^6.3.1
  http: ^1.2.2
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
   - assets/
   - .env